import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../../globals.css";
import {NextIntlClientProvider} from "next-intl";
import {getMessages, setRequestLocale} from "next-intl/server";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function LocaleLayout({children, params}: {
    children: React.ReactNode;
    params: { locale: 'en' | 'de' }
}) {
    // @ts-ignore
    const {locale}: 'en' | 'de' = await params;
    const messages = await getMessages();

    setRequestLocale(locale);
    return (
        <html lang={locale}>
        <body className={`relative overflow-hidden`}>
        <NextIntlClientProvider messages={messages}>

            <div className="popup">
                <h2>CONGRATS!</h2>
                <p>YOU HAVE WON:</p>

                <div className="content">
                    <div className="content-image">
                        <img src="/ezgif-2-572a4b516b%201.png" alt="" className="girl"/>
                    </div>
                    <p>
                        500% Welcome Bonus up to €6,000 and 777 Free Spins
                    </p>
                </div>
                <a href="https://dreamplay.bet/?registration=true" className="button-claim">Claim</a>
            </div>
            {children}

        </NextIntlClientProvider>
        </body>
        </html>
    );
}
